repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: end-of-file-fixer

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff
        args: ["--line-length=100"]
        exclude: |
            (?x)^(
                .*\.ipynb$|
                .*scripts\.py$
            )
      # linter.
      - id: ruff-check
        types_or: [ python, pyi ]
        args: [ --fix ]

-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        types_or: [python]
