repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: end-of-file-fixer

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.287
    hooks:
    -   id: ruff
        args: ["--line-length=100"]
